const data = {
    ecMemberTableData : [
        {
            name : 'Saleh Mahfoudh',
            position : 'Member',	
            startDate : '2021-06-16',
            status : 'Active'
        },
        {
            name : 'Faisal Gawas',
            position : 'Asst. Program Director',
            startDate : '2019-06-16',
            status : 'Terminated'
        },
        {
            name : 'Al Abri Falsal',
            position : 'Asst. Program Director',
            startDate : '2021-06-16',
            status : 'Active'
        },
    ],
    adminTableData : [
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Requested',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : undefined,
            ecSectionHeadComments : undefined,
            gmeDirectorComments : undefined,
            vppaComments : undefined,
            executivePresidentComments : undefined,
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Hilal basheer',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Member',
            status : 'Submitted to EC Section Head',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : undefined,
            gmeDirectorComments : undefined,
            vppaComments : undefined,
            executivePresidentComments : undefined,
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Submitted to GME Director',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : undefined,
            vppaComments : undefined,
            executivePresidentComments : undefined,
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Submitted to VPAA',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : undefined,
            executivePresidentComments : undefined,
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Submitted to Executive President',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : undefined,
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Approved',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : undefined,
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'No Objection Letter Pending',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : undefined,
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Membership QARAR Pending',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            membershipQararLink : undefined,
            applicantDocuments : undefined,
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Membership QARAR Generated',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            membershipQararLink : 'link',
            applicantDocuments : 'link'
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Pending Documents from Applicant',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            membershipQararLink : 'link',
            applicantDocuments : 'link'
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Pending Document Verification',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            membershipQararLink : 'link',
            applicantDocuments : 'link'
        },
        {
            name : 'Al Abri Ibraham',
            email : 'ibraham@omsb.com',
            civilId : '9786532151',
            trainingSite : 'Khoula Hospital',
            position : 'Program Director',
            status : 'Added as EC Member',
            applicationStatus : [
                { stage : 'Requested', status : 'Completed', date : '2022-09-21 10:00:00 AM', by : 'Madan Al Abri'},
                { stage : 'Submitted to EC Section', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to EC Section Head', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to Executive President', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'No Objection Letter', status : 'Pending', date : null, 'by' : null },
                { stage : 'Membership QARAR', status : 'Pending', date : null, 'by' : null },
                { stage : 'Contact Applicant', status : 'Pending', date : null, 'by' : null },
                { stage : 'Pending Documents', status : 'Pending', date : null, 'by' : null },
                { stage : 'Document Verification', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added as EC Member', status : 'Pending', date : null, 'by' : null },
              ],
            ecSectionComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            ecSectionHeadComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            gmeDirectorComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            vppaComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            executivePresidentComments : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsToEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            commentsFromEmployer : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, amet perferendis culpa consectetur cupiditate molestias. Dignissimos?',
            membershipQararLink : 'link',
            applicantDocuments : 'link'
        },
    ]
}

export { data };