const data = {
    tableData : [
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Requested',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Pending', date : null, 'by' : null },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : null,
            commentsFromGmeDirector: null,
            commentsFromVpaa: null,
            commentsFromEacRapporteur: null,
            formNumber : null
        },
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Submitted to GME Director',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali' },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromGmeDirector: null,
            commentsFromVpaa: null,
            commentsFromEacRapporteur: null,
            formNumber : null
        },
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Submitted to VPAA',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali' },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromGmeDirector: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromVpaa: null,
            commentsFromEacRapporteur: null,
            formNumber : null
        },
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Added to EAC Meeting agenda',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali' },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromGmeDirector: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromVpaa: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromEacRapporteur: null,
            formNumber : null
        },
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Approved',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali' },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromGmeDirector: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromVpaa: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromEacRapporteur: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            formNumber : null
        },
        {
            formName : 'Form Name Sample',
            commonOrProgramSpecific : 'Common',
            purpose : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, atque deserunt sint ipsam temporibus ut.',
            applicableFor : ['ENT', 'Anesthesia'],
            conductedBy : 'Al Abri Ibraham',
            intendedFor : 'Rotation Supervisor',
            whenMatched : 'Rotation Supervisor',
            whenAvailable : '1 week before end of the program',
            whenDue : '14 days from Block end date',
            blockOrAnnualRequirement : 'Block Requirement',
            mandatory : 'Yes',
            minimumRequiredNumber : '1, 2, 3.. per Block',
            requestedBy : 'Madan Al Abri',
            requestedOn : '2022-10-12',
            status : 'Form Submitted',
            applicationStatus : [
                { stage : 'Requested', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali'},
                { stage : 'Submitted to GME Director', status : 'Complete', date : '2022-11-25 10:00:00 AM', by : 'Abdel Maddali' },
                { stage : 'Submitted to VPAA', status : 'Pending', date : null, 'by' : null },
                { stage : 'Added to EAC Meeting agenda', status : 'Pending', date : null, 'by' : null },
                { stage : 'Approval', status : 'Pending', date : null, 'by' : null },
                { stage : 'Form Submitted', status : 'Pending', date : null, 'by' : null },
            ],
            commentsFromAP : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromGmeDirector: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromVpaa: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            commentsFromEacRapporteur: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tenetur assumenda cupiditate? Similique, eum aliquam.',
            formNumber : 'CS32131321'
        },

    ]
    
}

export { data };