const data = {
    nominees : [
        'Abdel Maddali',
        'Abu Nasser',
        'Al Abri Falsal',
        'Al Abri Ibraham',
        'Faisal Gawas',
        'Hilal basheer',
        'Madan Al Abri',
        'Madan Khan',
        'Saleh Mahfoudh',
        'Abdel Maddali',
        'Abu Nasser',
        'Al Abri Falsal',
        'Al Abri Ibraham',
        'Faisal Gawas',
        'Hilal basheer',
        'Madan Al Abri',
        'Madan Khan',
        'Saleh Mahfoudh',
        'Abdel Maddali',
        'Abu Nasser',
        'Al Abri Falsal',
        'Al Abri Ibraham',
        'Faisal Gawas',
        'Hilal basheer',
        'Madan Al Abri',
        'Madan Khan',
        'Saleh Mahfoudh',
        'Abdel Maddali',
        'Abu Nasser',
        'Al Abri Falsal',
        'Al Abri Ibraham',
        'Faisal Gawas',
        'Hilal basheer',
        'Madan Al Abri',
        'Madan Khan',
        'Saleh Mahfoudh',
        'Abdel Maddali',
        'Abu Nasser',
        'Al Abri Falsal',
        'Al Abri Ibraham',
        'Faisal Gawas',
        'Hilal basheer',
        'Madan Al Abri',
        'Madan Khan',
        'Saleh Mahfoudh',
    ]
}

export {data}