const ListJs = [
  {
    college : 'AIMS College',
    program: 'Fashion Design Diploma (2 year)',
    studentRollNumber: 'AIMSSTD003',
    studentName: 'Anupama D	',
    intakeYear: '2020	',
    belongingQuota: null,
    admissionTakenQuota: null,
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BCA',
    studentRollNumber: 'Std1010	',
    studentName: 'VIKAS',
    intakeYear: '2020	',
    belongingQuota: 'Backward Class Block `A`',
    admissionTakenQuota: 'All India Open',
    studentFeeCategory: 'Management',
    studentGroup: 'Group A',
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BACHELOR OF COMPUTER SCIENCE ENGINEERING	',
    studentRollNumber: 'KT002	',
    studentName: 'Aparna',
    intakeYear: '2021',
    belongingQuota: 'Haryana General Category	',
    admissionTakenQuota: 'Haryana General Category	',
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BACHELOR OF COMPUTER SCIENCE ENGINEERING	',
    studentRollNumber: 'KT003	',
    studentName: 'Anjali	',
    intakeYear: '2021	',
    belongingQuota: 'Haryana General Category	',
    admissionTakenQuota: 'Haryana General Category	',
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BACHELOR OF COMPUTER SCIENCE ENGINEERING	',
    studentRollNumber: 'KT004',
    studentName: 'Mahesh',
    intakeYear: '2021',
    belongingQuota: 'Haryana General Category',
    admissionTakenQuota: 'Haryana General Category',
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'Btech CSE',
    studentRollNumber: 'KT2002',
    studentName: 'Shweta',
    intakeYear: '2021',
    belongingQuota: 'All India Open',
    admissionTakenQuota: 'Haryana General Category',
    studentFeeCategory: 'General',
    studentGroup: 'Group A',
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BACHELOR OF COMPUTER SCIENCE ENGINEERING',
    studentRollNumber: 'KT005',
    studentName: 'Bhavana',
    intakeYear: '2021',
    belongingQuota: 'Haryana General Category',
    admissionTakenQuota: 'Haryana General Category',
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'Fashion Design Diploma (2 year)',
    studentRollNumber: 'AIMSSTD001',
    studentName: 'Aishwarya A',
    intakeYear: '2020',
    belongingQuota: null,
    admissionTakenQuota: null,
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'Fashion Design Diploma (2 year)',
    studentRollNumber: 'AIMSSTD002',
    studentName: 'AbhishekB B',
    intakeYear: '2020',
    belongingQuota: null,
    admissionTakenQuota: null,
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BACHELOR OF COMPUTER SCIENCE ENGINEERING	',
    studentRollNumber: 'KT001	',
    studentName: 'Anupradha',
    intakeYear: '2021',
    belongingQuota: 'Haryana General Category',
    admissionTakenQuota: 'Haryana General Category',
    studentFeeCategory: 'General',
    studentGroup: 'Group A	',
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'Bsc in Fine Arts	',
    studentRollNumber: 'AA004321',
    studentName: 'ANUJ	',
    intakeYear: '2021	',
    belongingQuota: 'All India Open	',
    admissionTakenQuota: 'Haryana General Category	',
    studentFeeCategory: 'Management',
    studentGroup: 'Group B',
    isSelected:false
  },
  {
    college : 'AIMS College',
    program: 'BBM(2year)	',
    studentRollNumber: '1210321002184	',
    studentName: 'NISHANT',
    intakeYear: '2021',
    belongingQuota: 'Haryana General Category',
    admissionTakenQuota: 'Haryana General Category',
    studentFeeCategory: null,
    studentGroup: null,
    isSelected:false
  },
];

export { ListJs };
