const data = {
  tableData : [
    {
      name : 'Madan Al Abri',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-01-15',
      completedResidentDevelopment: 'Yes',
      status : 'Requested',
      applicationStatus : [
        { stage : 'Request submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Document Submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Achievements Submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Assessments and Performance Section Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Request For Cancellation Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Saleh Mahfoudh',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Document Submission',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Achievements Submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Assessments and Performance Section Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Request For Cancellation Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Madan Khan',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Graduation Achievements Submission',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Assessments and Performance Section Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Request For Cancellation Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Abdel Maddali',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Assessments and Performance Section Approval',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Request For Cancellation Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Al Abri Falsal',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Request For Cancellation Release',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Al Abri Ibraham',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Letter of Cancellation of Release',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Abu Nasser',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Letter of Cancellation of Released',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Cancellation QARAR',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Cancellation QARAR Submitted',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Clearance Pending',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Graduation Booklet',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Graduation Booklet Generated',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Booklet Generated', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending TA Director Approval',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Booklet Generated', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending TA Director Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Chairman/PD Approval',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Booklet Generated', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending TA Director Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Chairman/PD Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Pending Executive President Approval',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Booklet Generated', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending TA Director Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Chairman/PD Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Executive President Approval', status : 'Pending', date : 'N/A', by : 'N/A'},
        { stage : 'Completed', status : 'Pending', date : 'N/A', by : 'N/A'}
      ]
    },
    {
      name : 'Faisal Gawas',
      annualEvaluations : 'Yes',
      passStatus: 'Yes',
      fitarComplition: 'Yes',
      fitarComplitionDate: '2021-02-05',
      completedResidentDevelopment: 'Yes',
      status : 'Completed',
      applicationStatus : [
        { stage : 'Request submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Document Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Achievements Submission', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Assessments and Performance Section Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Request For Cancellation Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Letter of Cancellation of Release', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Letter of Cancellation of Released', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Cancellation QARAR', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Cancellation QARAR Submitted', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Clearance Pending', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Graduation Booklet', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Graduation Booklet Generated', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending TA Director Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Chairman/PD Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Pending Executive President Approval', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'},
        { stage : 'Completed', status : 'Complete', date : '2022-11-28 08:00:00 AM', by : 'Al Madan Khan'}
      ]
    },
  ]
}

export {data}