const data = {
    tableData : [
        {
            requestId: '1235-053435',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Submit - By PD',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by Legal Affairs', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by VPAA', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '9875-5647852',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Submit - By TAFUS',
            applicationStatus : [
                { stage : 'Submission by TAFUS', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by Legal Affairs', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by VPAA', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '5467-45679632',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Under Legal review',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by VPAA', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '1482-21317984',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Pending VPAA approval',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Approved by EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '6547-78963122',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Pending EP approval',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '3697-45691234',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Pending QARAR',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Generate QARAR', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '7896-253435',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Pending QARAR approval from Legal Affairs',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Generate QARAR', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from Legal', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '4568-081435',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Pending QARAR approval from ER',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Generate QARAR', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from Legal', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from EP', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '9678-883435',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Digital Signature Pending',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Generate QARAR', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from Legal', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' Digital Signature Pending', status : 'Pending',  date : 'N/A', by: 'N/A'},
                { stage : ' Request Completion', status : 'Pending',  date : 'N/A', by: 'N/A'},
            ]
        },
        {
            requestId: '9658-053435',
            dateOfRequest : '15-09-2022 08:35PM',
            trainee : 'Madan Al Abri',
            programName : 'ENT',
            status: 'Complete',
            applicationStatus : [
                { stage : 'Submission by PD', status : 'Complete',  date : '2022-09-25 09:30AM', by: 'Al Abri Ibraham'},
                { stage : 'Approved by TAFUS', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by Legal Affairs', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by VPAA', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Approved by EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : 'Generate QARAR', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from Legal', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' QARAR approval from EP', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' Digital Signature Pending', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
                { stage : ' Request Completion', status : 'Complete',  date : 'Hilal basheer', by: '2022-09-28 09:30AM'},
            ]
        },
    ]
}

export {data}