const data = {
    rotationObject : {
        'year' : 'R1',
        'name' : 'Anesthesia for General Surgery',
        'type' : 'Core',
        'code' : 'ANGS',
        'isOwnedByRotation' : 'Yes',
        'numberOfBlocks' : '65',
        'trainingSites' : 'AFH, Khoula Hospital, Royal Hospital, SQUH',
        'description' : '<p>The main objective of this rotation is to expose the residents to both stable and unstable adult patients with cardiac disease and thereafter to develop the knowledge along with technical and therapeutic skills to manage such patients. This rotation aims to strengthen the anesthesia resident’s ability to deal with critically ill adult patients with cardiac dysfunction in the perioperative period.</p>',
        'objectives' : [
            {objectiveName : 'Medical Knowledge', objectiveContent : `<ul><li>Demonstrate knowledge of the basic sciences as applicable to cardiology, including anatomy, physiology, pharmacology, biochemistry and physics.</li><li>Demonstrate knowledge of general internal medicine with particular reference to the cardiovascular system.&nbsp;</li><li>Demonstrate knowledge of the pathophysiology, assessment and treatment of common cardiac problems<ul><li>Chest pain assessment</li><li>Myocardial ischemia/infarction o Congestive heart failure</li><li>Acute pulmonary edema</li><li>Cardiogenic shock o Arrhythmias o Use of pacemakers</li><li>Cardioversion</li></ul></li><li>Develop clinical expertise with acutely ill cardiac patients<ul><li>Clinical assessment: history, physical, labs</li><li>Development and execution of treatment plans under supervision</li></ul></li><li>Demonstrate knowledge of specialized means of assessment and monitoring of the CVS:&nbsp;<ul><li>Echocardiography</li><li>EKG</li></ul></li><li>Demonstrate knowledge of age related variables in medicine as they apply to adult and geriatric patient care.</li><li>Demonstrate clinical skills necessary for basic resuscitation and life support as practiced in coronary care facilities.</li><li>Demonstrate clinical skills necessary to coronary care medicine including the ability to investigate, diagnose, and manage appropriately factors that influence a patient's medical and surgical care.</li><li>Recognize that prior to provision of anesthetic care specific medical/cardiac intervention and modification of risk factors may be required.</li><li>Demonstrate competence in all technical procedures commonly employed in CCU, including intravenous, central venous, arterial cannulations, and endotracheal intubation.</li></ul>`},
            { objectiveName : 'Interpersonal and Communications Skills', objectiveContent : `<ul><li>Establish a professional and empathetic relationship with patients and families.</li><li>Obtain and collate relevant history from patients and families.</li><li>Listen effectively.</li><li>Discuss appropriate information with patients and families and other members of the health care team about daily patient progress.</li><li>Communicate effectively with the attending cardiologist relevant clinical information on which decisions will be based.</li><li>Keep clear, concise and legible documentation of daily patient progress in the patients’ hospital chart.</li><li>Communicate effectively (both in written and verbal form) a concise yet complete medical summary to the next medical team assuming patient care.</li><li>Consult effectively with other physicians and health care professionals.</li><li>Function as active member of the health care team in the CCU including appropriate use of consultation.</li></ul>` },
            { objectiveName : 'Systems-Based Practice', objectiveContent : `<ul><li>Understand the limited physical capacity of coronary care unit and manage admissions and discharges in such a way to not compromise patient’s care; allocate finite health care resources wisely.</li><li>Work effectively and efficiently in a health care organization.</li><li>Utilize information technology to optimize patient care and lifelong learning.  Demonstrate principles of quality assurance and conduct morbidity and mortality reviews.</li></ul>` },
            { objectiveName : 'Practice-Based Learning and Improvement', objectiveContent : `<ul><li>Develop, implement and monitor a personal continuing education strategy.</li><li>Critically appraise sources of medical information.</li><li>Facilitate learning of patients, students and other health professionals</li><li>Identify the important determinants of health affecting patients.</li><li>Contribute effectively to improve health of patients and communities.</li><li>Recognize and respond to those issues where advocacy is appropriate.</li><li>Develop an approach to dealing with medical errors.</li></ul>` },
            { objectiveName : 'Professionalism ', objectiveContent : `<ul><li>Deliver highest quality care with integrity, honesty and compassion.</li><li>Exhibit appropriate personal and interpersonal professional behaviors.</li><li>Practice medicine ethically consistent with the obligations of a physician.&nbsp;</li><li>Include the patient/family in discussions concerning appropriate diagnostic and management procedures.</li><li>Respect the opinions of fellow consultants and referring physicians in the management of patient problems and be willing to provide means whereby differences of opinion can be discussed and resolved.</li><li>Show recognition of limits of personal skill and knowledge by appropriately consulting other physicians and paramedical personnel when caring for the patient.</li></ul>` },
            { objectiveName : 'Patient Care', objectiveContent : `<ul><li>Provide patient care that is compassionate, appropriate and effective for the treatment of health problems and the promotion of health.</li><li>Demonstrate appropriate clinical judgment and proper patient care plan when discussing patient’s clinical situation with the attending cardiologist.&nbsp;</li><li>Show recognition of limits of personal skills and knowledge by appropriately consulting other physicians and paramedical personnel when caring for the patient.</li></ul>` },
            
        ],
        'methodOfAssessments' : [
            {methodName : 'ITER'},
            {methodName : 'Case Based Discussion'},
            {methodName : 'Direct observation of procedure'}
        ]

    }
}

export {data}