const data = {
    syllabusContents : [
        { name : 'PREOPERATIVE ASSESSMENT', content : `<ul><li>The ASA classification and GCS&nbsp;</li><li>The interpretation of relevant preoperative investigations&nbsp;</li><li>Restriction of food and fluid by mouth, cessation of smoking, correction of dehydration</li><li>Assessment of difficulties in airway management and the importance of ‘shared airway’</li><li>Implications for anesthesia of common medical conditions (ischemic heart disease, hypertension, bronchial asthma, diabetes, rheumatoid arthritis, etc.)</li><li>Anesthetic implications of current drug therapy and whether it should be continued, stopped or modified preoperatively</li><li>Need for and methods of preoperative DVT prophylaxis</li><li>The importance of anesthetic and genetic disease history with respect to suxamethonium apnea, anaphylaxis, and malignant hyperthermia  Postoperative analgesic needs</li><li>Assessment of whether postoperative ICU or HDU care is required</li><li>Importance of consent</li><li>Dangers of repeat anesthesia</li></ul>`,
        editable : false},
        { name : 'PREMEDICATION', content : `<ul><li>Rationale use for premedicant drugs</li><li>Choice of drugs, advantages and disadvantages</li><li>Rationale for antacid and prokinetic premedication</li><li>Rationale for DVT prophylaxis</li><li>Understanding of causes and implications of delayed gastric emptying</li></ul>`,
        editable : false},
        { name : 'ANESTHESIA, HDU AND ICU EQUIPMENT; MONITORING AND SAFETY', content : `<ul><li>Physical principles underlying the function of the anesthetic machine, pressure regulators, flowmeters, vaporizers, breathing systems</li><li>Chemistry of absorption of carbon dioxide&nbsp;</li><li>Principles of end tidal capnography and pulse oximetry&nbsp;</li><li>Principles of lung ventilators, disconnection monitors&nbsp;</li><li>Manufacture and storage of oxygen, nitrous oxide, carbon dioxide, compressed air, gas cylinders&nbsp;</li><li>Pipeline and suction systems&nbsp;</li><li>Basis of pre-use check of anesthetic machines, breathing circuits and monitors&nbsp;</li><li>Airways, tracheal tubes, tracheostomy tubes, emergency airways and trolley, laryngeal masks, oxygen therapy equipments, self-inflating bags&nbsp;</li><li>The content of an anesthetic record&nbsp;</li><li>Function and use of resuscitation equipment, transfusion devices</li><li>Humidification devices&nbsp;</li><li>Anesthetic gas scavenging systems, humidity&nbsp;</li><li>Sterilization and cleaning of equipment&nbsp;</li><li>Electrical safety</li><li>Characteristics of intravenous cannulae, spinal and epidural needles</li></ul>`,
        editable : false}
    ]
}

export {data}