import { Countries } from "src/app/enums/countries";

const data = {
    countryList : Countries.countryList,
    formData : {
        name : 'Abbas Al Ajmi',
        arabicName : 'عباس أل أجمع',
        nationalID : '97845468132',	
        specialty : 'Anesthesia',
        subspecialty : 'Subspecialty Value 1',
        trainingType : 'Value 2',
        institution : 'Khoula Hospital',	
        country : 'Oman',	
        startDate : '2021-01-06',
        completionDate : '2022-05-15',
        gender : 'Male',
        trainingStatus : 'Status 1',	
        trainingStatusRemark : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam autem dolorem voluptatibus rerum voluptate praesentium?',	
        sponsor : 'MOH', employer : 'Employer 1',	
        evaluationReports : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus esse incidunt corporis veniam tempora! Quis, dignissimos?',
        submittedCertificateOfCompletion : 'Yes'	,
        email1 : 'Abbas@email.com'	,
        email2 : 'Abbas@email.com'	,
        localPhoneNo : '+968456789'	,
        internationalPhoneNo : '+968456789'
    },
    tableData: [
        {
            name : 'Abbas Al Ajmi',
            arabicName : 'عباس أل أجمع',
            nationalID : '97845468132',	
            specialty : 'Anesthesia',
            subspecialty : 'Subspecialty Value 1',
            trainingType : 'Value 2',
            institution : 'Khoula Hospital',	
            country : 'Oman',	
            startDate : '2021-01-06',
            completionDate : '2022-05-15',
            gender : 'Male',
            trainingStatus : 'Status 1',	
            trainingStatusRemark : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam autem dolorem voluptatibus rerum voluptate praesentium?',	
            sponsor : 'MOH', employer : 'Employer 1',	
            evaluationReports : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus esse incidunt corporis veniam tempora! Quis, dignissimos?',
            submittedCertificateOfCompletion : 'Yes'	,
            email1 : 'Abbas@email.com'	,
            email2 : 'Abbas@email.com'	,
            localPhoneNo : '+968456789'	,
            internationalPhoneNo : '+968456789'
        },
        {
            name : 'Saleh Mahfoudh',
            arabicName : 'عباس أل أجمع',
            nationalID : '97845468132',	
            specialty : 'Anesthesia',
            subspecialty : 'Subspecialty Value 1',
            trainingType : 'Value 2',
            institution : 'Khoula Hospital',	
            country : 'Oman',	
            startDate : '2021-01-06',
            completionDate : '2022-05-15',
            gender : 'Male',
            trainingStatus : 'Status 1',	
            trainingStatusRemark : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam autem dolorem voluptatibus rerum voluptate praesentium?',	
            sponsor : 'MOH', employer : 'Employer 1',	
            evaluationReports : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus esse incidunt corporis veniam tempora! Quis, dignissimos?',
            submittedCertificateOfCompletion : 'Yes'	,
            email1 : 'Abbas@email.com'	,
            email2 : 'Abbas@email.com'	,
            localPhoneNo : '+968456789'	,
            internationalPhoneNo : '+968456789'
        },
        {
            name : 'Abdel Maddali',
            arabicName : 'عباس أل أجمع',
            nationalID : '97845468132',	
            specialty : 'Anesthesia',
            subspecialty : 'Subspecialty Value 1',
            trainingType : 'Value 2',
            institution : 'Khoula Hospital',	
            country : 'Oman',	
            startDate : '2021-01-06',
            completionDate : '2022-05-15',
            gender : 'Male',
            trainingStatus : 'Status 1',	
            trainingStatusRemark : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam autem dolorem voluptatibus rerum voluptate praesentium?',	
            sponsor : 'MOH', employer : 'Employer 1',	
            evaluationReports : 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus esse incidunt corporis veniam tempora! Quis, dignissimos?',
            submittedCertificateOfCompletion : 'Yes'	,
            email1 : 'Abbas@email.com'	,
            email2 : 'Abbas@email.com'	,
            localPhoneNo : '+968456789'	,
            internationalPhoneNo : '+968456789'
        },
    ]

}

export {data};