const data = {
  rotationCodes: [
    "OBGYN-ANW-RH",
    "OBGYN-CLINIC-RH",
    "OBGYN-ANS-RH",
    "EM-EM-KH",
    "OBGYN-OT-RH",
    "OBGYN-RSCH(STAGE 1)-RH",
    "OBGYN-CLINIC-SQUH",
    "PEDS-NICU-RH",
    "OBGYN-ANX-RH",
    "OBGYN-ANA-RH",
    "EM-ER-KH",
    "OBGYN-ON-RH",
    "OBGYN-RSCH(STAGE 2)-RH",
    "EM-CLINIC-SQUH",
    "PEDS-NICU-SQUH",
    "OBGYN-ANB-RH",
    "OBGYM-CLINIC-RH",
    "OBGYN-ANC-RH",
    "EM-EN-KH",
    "OBGYN-OS-RH",
    "OBGYN-RSCH(STAGE 3)-RH",
    "PEDS-CLINIC-SQUH",
    "OBGYN-ANJ-RH",
    "OBGYR-CLINIC-RH",
    "OBGYN-ANI-RH",
    "EM-EB-KH",
    "OBGYN-OA-RH",
    "OBGYN-RSCH(STAGE 4)-RH",
    "OBGYN-CLINIC-SQUH",
    "AL",
    "ML"
  ],
  students: [
    { name: "Al Abri Falsal", program: 'Anaesthesia', year: 'R3', omsbNumber : '19-251'},
    { name: "Al Abri Ibraham", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-601'},
    { name: "Fahad Al Khatri", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-221'},
    { name: "Yasser Al Ajmi", program: 'Anaesthesia', year: 'R3', omsbNumber : '21-412'},
    { name: "Yasser Al Maamari", program: 'Anaesthesia', year: 'R3', omsbNumber : '19-394'},
    { name: "Al Raisi", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-205'},
    { name: "Abba Abri Falsal", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-135'},
    { name: "Abba Abri Ibraham", program: 'Anaesthesia', year: 'R3', omsbNumber : '22-591'},
    { name: "Fahad Al Ibraham", program: 'Anaesthesia', year: 'R3', omsbNumber : '22-571'},
    { name: "Abba Al Ajmi", program: 'Anaesthesia', year: 'R3', omsbNumber : '22-412'},
    { name: "Raisi Al Maamari", program: 'Anaesthesia', year: 'R3', omsbNumber : '19-351'},
    { name: "Abdulaziz Raisi", program: 'Anaesthesia', year: 'R3', omsbNumber : '19-412'},
    { name: "Al Falsal", program: 'Anaesthesia', year: 'R3', omsbNumber : '19-812'},
    { name: "Fahad Abri Ibraham", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-471'},
    { name: "Fahad Al Maamari", program: 'Anaesthesia', year: 'R3', omsbNumber : '21-360'},
    { name: "Abba Al Fahad", program: 'Anaesthesia', year: 'R3', omsbNumber : '20-782'},
  ],
  faculty: [
    {name : 'Al Abri Falsal'},
    {name : 'Al Abri Maamari'},
    {name : 'Al Abri Ibraham'},
    {name : 'Fahad Al Khatri'},
    {name : 'Yasser Al Ajmi'},
    {name : 'Yasser Al Maamari'},
    {name : 'Al Raisi'},
    {name : 'Abba Abri Falsal'},
    {name : 'Fahad Al Ibraham'},
    {name : 'Raisi Al Maamari'},
    {name : 'Fahad Abri Ibraham'},
    {name : 'Abri Fahad Ibraham'},
    {name : 'Abdulaziz Raisi'}
  ],
};

export { data };
